[package]
name = "mseed3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
serde_json = "1"
thiserror = "1.0"
chrono = "0.4"
crc = "2.0"